### ISSUE TITLE
Comments for 03-GKE-storage

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-kubernetes#15]
Comments for  https://cms-opendata-workshop.github.io/workshop-lesson-kubernetes/03-GKE-storage/index.html

Minor fixes to the instructions:

- [x] remove "to which" from "setup a volume where to which the output files will be written" 
  -  (1st paragraph)
- [x] remove one of these: "Replace `<NUMBER>` as before. Also, adjust the `<NUMBER>`." 
   - (under `kubectl get -n argo svc nfs-server-<NUMBER>....` )
- [x] remove `kubectl get pods -n argo` after `kubectl expose deployment http-fileserver ...` as it repeats just under
- [x] remind of `argo delete @latest -n argo` again at the end

For g8s 1.16 compatibility:

- [x] change the first line of 001-nfs-server.yaml to `apiVersion: apps/v1`
- [x] add `selector` in deployment-http-fileserver.yaml:
```
# deployment-http-fileserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: http-fileserver
  name: http-fileserver
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: http-fileserver
  template:
...
```
