### ISSUE TITLE
Comments for 04-download_data

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop-lesson-kubernetes#16]
Comments to https://cms-opendata-workshop.github.io/workshop-lesson-kubernetes/04-download_data/index.html

Minor fixes to the instructions

- [ ] one could make even more clearer that what is explained under "Getting the tool", "Listing files", and "Downloading files" are not needed for the cloud tutorial but to understand the tool. Group them together in a common section "Learning the tool" or similar with an introduction sentence explaining that?
- [x] give the explicit commands for "you can monitor the progress both via the pod and the job resources"
```
kubectl get pod -n argo
kubectl get job -n argo
```
- [x] explain where did the downloaded file go (instruct to have a look through the fileserver after doing again `kubectl expose deployment http-fileserver -n argo --type LoadBalancer --port 80 --target-port 80` or `kubectl exec pod/pv-pod -n argo -- ls  /mnt/data/`

- [ ] Issues to be solved for the file download through opendata-client-go, 
  - http protocol truncated after 1 GB
    - continues where it stopped so as a workaround can be repeated in a workflow(*) but a better solution would be welcome
  - xrootd protocol prohibitively slow and most often fails due some server instabilities
  - the standard opendata-client does not have the xrootd protocol in the container, yet, and for the http, it stops at 1 G and a new download restarts from zero
  

(*) For the record, a possible argo workflow for recursive download, needs the total size and the record number (NB that this does not work for AOD because they are many files and after the 1 G limit, the transfer continues with a new file and would stop only when 1 G of **all** AOD files will have been downloaded):

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: download-recursive-
spec:
  entrypoint: download
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs
  templates:
  - name: download
    steps:
    # download the file
    - - name: download-file
        template: download-file
    # check if it is complete
    - - name: iscomplete
        template: iscomplete
    # direct to final step or redo
    - - name: complete
        template: complete                 # call complete template if "complete"
        when: "{{steps.iscomplete.outputs.parameters.completeness}} == complete"
      - name: incomplete                     # keep downloading if "incomplete"
        template: download
        when: "{{steps.iscomplete.outputs.parameters.completeness}} == incomplete"
  - name: download-file
    script:
      image: clelange/cernopendata-client-go
      command: []
      args: ["download", "-r", "12355", "-o", "/mnt/vol"]
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
  - name: iscomplete
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        totsize=10731401995
        echo "Total size: " $totsize
        currentsize=$(ls -l /mnt/vol/12355 | awk '{print $5}' | grep [0-9])
        echo "Downloaded: " $currentsize
        if [ $currentsize -lt $totsize ] ; then myvar="incomplete"; else myvar="complete"; fi
        echo $myvar > /tmp/iscomplete.txt
        echo $myvar
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol
    outputs:
      parameters:
      - name: completeness       # complete or not
        valueFrom:
          path: /tmp/iscomplete.txt
  - name: complete
    container:
      image: alpine:3.6
      command: [sh, -c]
      args: ["echo \"The transfer is complete\""]
```
